# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  win: circleci/windows@2.4
  
jobs:
  test:
    machine:
      image: windows-server-2019-cuda:current
    steps:
      - checkout
      - run:
          name: Run tests
          command: dotnet test
          
workflows:
  example:
    jobs:
      - test
