name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    strategy:
      matrix:
        configuration: [ Release ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      # Restore Dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build Dependencies
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # Execute all unit tests in the solution
      - name: Execute tests
        run: dotnet test

      # Folder 1
      - name: Get files
        run: ls TestRail

      - name: Into Folder
        run: ls TestRail/bin

      - name: Get files 1
        run: ls TestRail/bin/Debug
        
      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          #allure_results: TestRail/bin/Release/net8.0/allure-results
          allure_results: build/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history