name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [ Release ]

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
           
      # Restore Dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build Dependencies
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # Execute all unit tests in the solution
      - name: Execute tests
        run: dotnet test
